using System.Globalization;

namespace ProxysqlAdminUi.Web.Services;

public sealed class LocalizationService
{
    private static readonly IReadOnlyDictionary<string, string> Chinese = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["Home"] = "首页",
        ["MySQL Users"] = "MySQL 用户",
        ["MySQL Servers"] = "MySQL 服务器",
        ["Rules"] = "规则",
        ["Query Digest"] = "查询摘要",
        ["Global Variables"] = "全局变量",
        ["Actions"] = "操作",
        ["Language"] = "语言",
        ["English"] = "English",
        ["Chinese"] = "中文",
        ["Log in"] = "登录",
        ["Log in to ProxySql Admin UI"] = "登录 ProxySQL Admin UI",
        ["Password"] = "密码",
        ["Remember me"] = "记住我",
        ["Invalid login attempt."] = "登录失败，请检查用户名和密码。",
        ["Query Cache Efficiency"] = "查询缓存效率",
        ["Cache hit rate"] = "缓存命中率",
        ["Total Queries"] = "查询总数",
        ["Cached"] = "已缓存",
        ["Uncached"] = "未缓存",
        ["Memory Usage"] = "内存使用",
        ["Query Cache:"] = "查询缓存：",
        ["Connection Pool:"] = "连接池：",
        ["Total Allocated:"] = "已分配总量：",
        ["Monitor Health"] = "监控健康状态",
        ["Monitor Workers:"] = "监控线程：",
        ["Connect Checks"] = "连接检查",
        ["Ping Checks"] = "Ping 检查",
        ["DNS Cache"] = "DNS 缓存",
        ["Uptime"] = "运行时间",
        ["Server Status"] = "服务器状态",
        ["Online"] = "在线",
        ["Shunned"] = "已隔离",
        ["Offline"] = "离线",
        ["Total"] = "总数",
        ["Connection Health"] = "连接健康状态",
        ["Active Connections:"] = "活跃连接：",
        ["Total Created:"] = "创建总数：",
        ["Aborted:"] = "已中止：",
        ["ProxySQL All-Time Stats"] = "ProxySQL 累计统计",
        ["Total Queries:"] = "查询总数：",
        ["Slow Queries:"] = "慢查询：",
        ["Cache Hits:"] = "缓存命中：",
        ["Network Traffic"] = "网络流量",
        ["Frontend"] = "前端",
        ["Backend"] = "后端",
        ["Received:"] = "接收：",
        ["Sent:"] = "发送：",
        ["Refresh"] = "刷新",
        ["Main (editable)"] = "Main（可编辑）",
        ["Runtime (read-only)"] = "Runtime（只读）",
        ["Disk (read-only)"] = "Disk（只读）",
        ["Data source"] = "数据来源",
        ["This layer is read-only."] = "此层级仅供查看。",
        ["Add server"] = "新增服务器",
        ["Edit"] = "编辑",
        ["Delete"] = "删除",
        ["Cancel"] = "取消",
        ["Save"] = "保存",
        ["Save, load & persist"] = "保存、加载并持久化",
        ["Delete, load & persist"] = "删除、加载并持久化",
        ["Hostname is required"] = "主机名不能为空",
        ["Username is required"] = "用户名不能为空",
        ["GTID port"] = "GTID 端口",
        ["Max latency (ms)"] = "最大延迟（毫秒）",
        ["Use SSL"] = "使用 SSL",
        ["Compression"] = "压缩",
        ["Default hostgroup"] = "默认主机组",
        ["Attributes"] = "属性",
        ["Schema locked"] = "锁定数据库",
        ["Transaction persistent"] = "事务保持",
        ["Fast forward"] = "快速转发",
        ["Saving updates the ProxySQL memory table, loads MySQL servers to Runtime, and saves them to Disk."] = "保存会更新 ProxySQL 内存表，将 MySQL 服务器加载到运行时并保存到磁盘。",
        ["Saving updates the ProxySQL memory table, loads MySQL users to Runtime, and saves them to Disk."] = "保存会更新 ProxySQL 内存表，将 MySQL 用户加载到运行时并保存到磁盘。",
        ["This removes the server from ProxySQL, loads the new server configuration to Runtime, and saves it to Disk."] = "此操作会从 ProxySQL 删除服务器，将新服务器配置加载到运行时并保存到磁盘。",
        ["This removes the user from ProxySQL, loads the new user configuration to Runtime, and saves it to Disk."] = "此操作会从 ProxySQL 删除用户，将新用户配置加载到运行时并保存到磁盘。",
        ["Server"] = "服务器",
        ["Server added"] = "服务器已新增",
        ["Server updated"] = "服务器已更新",
        ["Server deleted"] = "服务器已删除",
        ["User added"] = "用户已新增",
        ["User updated"] = "用户已更新",
        ["User deleted"] = "用户已删除",
        ["The change is active in Runtime and saved to Disk."] = "变更已在运行时生效并保存到磁盘。",
        ["Failed to load server"] = "加载服务器失败",
        ["Failed to save server"] = "保存服务器失败",
        ["Failed to delete server"] = "删除服务器失败",
        ["Failed to load user"] = "加载用户失败",
        ["Failed to save user"] = "保存用户失败",
        ["Failed to delete user"] = "删除用户失败",
        ["No MySQL servers found."] = "未找到 MySQL 服务器。",
        ["Hostgroup"] = "主机组",
        ["Hostname"] = "主机名",
        ["Port"] = "端口",
        ["Status"] = "状态",
        ["Weight"] = "权重",
        ["Max connections"] = "最大连接数",
        ["Max replication lag"] = "最大复制延迟",
        ["Comment"] = "备注",
        ["Add MySQL server"] = "新增 MySQL 服务器",
        ["Add user"] = "新增用户",
        ["No MySQL users found."] = "未找到 MySQL 用户。",
        ["Username"] = "用户名",
        ["Active"] = "启用",
        ["Default HG"] = "默认主机组",
        ["Default schema"] = "默认数据库",
        ["Add MySQL user"] = "新增 MySQL 用户",
        ["Reset Statistics"] = "重置统计",
        ["Flush Query Cache"] = "清空查询缓存",
        ["Statistics reset"] = "统计已重置",
        ["ProxySQL statistics have been reset"] = "ProxySQL 统计信息已重置",
        ["Cache Flushed"] = "缓存已清空",
        ["Query cache has been flushed"] = "查询缓存已清空",
        ["Failed to load servers"] = "加载服务器失败",
        ["Failed to load users"] = "加载用户失败",
        ["Failed to load query rules"] = "加载查询规则失败",
        ["Failed to load global variables"] = "加载全局变量失败",
        ["MySQL Query Digest Statistics"] = "MySQL 查询摘要统计",
        ["Schema"] = "数据库",
        ["Client Address"] = "客户端地址",
        ["Query"] = "查询",
        ["Query Count"] = "查询次数",
        ["First Seen"] = "首次出现",
        ["Last Seen"] = "最后出现",
        ["Total Time"] = "总耗时",
        ["Min Time (μs)"] = "最小耗时（μs）",
        ["Max Time (μs)"] = "最大耗时（μs）",
        ["Rows Affected"] = "影响行数",
        ["Rows Sent"] = "返回行数",
        ["Rule ID"] = "规则 ID",
        ["No data to display"] = "暂无数据",
        ["Refresh Data"] = "刷新数据",
        ["Create Rule"] = "创建规则",
        ["Edit Rule"] = "编辑规则",
        ["The associated rule is unavailable."] = "关联规则不可用。",
        ["Cache 1 minute"] = "缓存 1 分钟",
        ["Cache 5 minutes"] = "缓存 5 分钟",
        ["Cache 10 minutes"] = "缓存 10 分钟",
        ["Cache 30 minutes"] = "缓存 30 分钟",
        ["Cache 1 hour"] = "缓存 1 小时",
        ["Cache 1 day"] = "缓存 1 天",
        ["Query Rules"] = "查询规则",
        ["Apply"] = "应用",
        ["Cache TTL (ms)"] = "缓存 TTL（毫秒）",
        ["Cache Empty Results"] = "缓存空结果",
        ["Timeout"] = "超时",
        ["Log"] = "日志",
        ["Schema Name"] = "数据库名称",
        ["Destination host group"] = "目标主机组",
        ["Digest Text"] = "摘要文本",
        ["Match Digest"] = "匹配摘要",
        ["Match Pattern"] = "匹配模式",
        ["Negate Match Pattern"] = "否定匹配模式",
        ["Replace Pattern"] = "替换模式",
        ["Processed Queries"] = "已处理查询",
        ["Cached Queries"] = "已缓存查询",
        ["Add rule"] = "新增规则",
        ["No query rules found."] = "未找到查询规则。",
        ["Value is required"] = "值不能为空",
        ["Variable Name"] = "变量名",
        ["Total Variables"] = "变量总数",
        ["Value"] = "值",
        ["Success"] = "成功",
        ["Variable updated"] = "变量已更新",
        ["Loading..."] = "加载中...",
        ["Error"] = "错误",
        ["An error occurred while processing your request."] = "处理请求时发生错误。",
        ["Request ID:"] = "请求 ID：",
        ["Advanced Settings"] = "高级设置",
        ["Cache TTL"] = "缓存 TTL",
        ["Cache Empty Result"] = "缓存空结果",
        ["Proxy Address"] = "代理地址",
        ["Proxy Port"] = "代理端口",
        ["Flag In"] = "输入标记",
        ["Flag Out"] = "输出标记",
        ["Next Query Flag In"] = "下一查询输入标记",
        ["RE Modifiers"] = "正则修饰符",
        ["Destination Hostgroup"] = "目标主机组",
        ["GTID From Hostgroup"] = "GTID 来源主机组",
        ["Mirror Flag Out"] = "镜像输出标记",
        ["Mirror Hostgroup"] = "镜像主机组",
        ["Cache Timeout"] = "缓存超时",
        ["Retries"] = "重试次数",
        ["Delay"] = "延迟",
        ["Multiplex"] = "连接复用",
        ["Error Message"] = "错误消息",
        ["OK Message"] = "成功消息",
        ["Reconnect"] = "重新连接",
        ["Sticky Connection"] = "粘性连接",
        ["Hours"] = "小时",
        ["Minutes"] = "分钟",
        ["Seconds"] = "秒",
        ["Milliseconds"] = "毫秒",
        ["Confirm Delete"] = "确认删除",
        ["Rule Details:"] = "规则详情：",
        ["Are you sure you want to delete Query Rule #"] = "确定要删除查询规则 #",
        ["The selected MySQL server was not found."] = "未找到所选 MySQL 服务器。",
        ["The selected MySQL user was not found."] = "未找到所选 MySQL 用户。",
        ["The selected query rule was not found."] = "未找到所选查询规则。",
        ["Failed to load query rule details."] = "加载查询规则详情失败。",
        ["Failed to delete query rule."] = "删除查询规则失败。",
        ["Query Rule #"] = "查询规则 #",
        [" has been deleted."] = " 已删除。"
    };

    public event Action? Changed;

    public string CurrentLanguage { get; private set; } = "en-US";

    public CultureInfo CurrentCulture => CultureInfo.GetCultureInfo(CurrentLanguage);

    public string this[string key] => CurrentLanguage.StartsWith("zh", StringComparison.OrdinalIgnoreCase)
        ? Chinese.GetValueOrDefault(key, key)
        : key;

    public string Get(string key) => this[key];

    public void SetLanguage(string language)
    {
        var normalized = language.StartsWith("zh", StringComparison.OrdinalIgnoreCase) ? "zh-CN" : "en-US";
        if (CurrentLanguage == normalized)
        {
            return;
        }

        CurrentLanguage = normalized;
        CultureInfo.CurrentCulture = CurrentCulture;
        CultureInfo.CurrentUICulture = CurrentCulture;
        Changed?.Invoke();
    }
}
